### ISSUE TITLE
Inspector cannot open trace from tslint

### ISSUE THREAD

**Issue by egamma** [octref/lsp-inspector#10]
@octref the attached file does not open in the inspector

[tslint-log.txt](https://github.com/octref/lsp-inspector/files/2115595/tslint-log.txt)

![image](https://user-images.githubusercontent.com/172399/41603941-4724e946-73de-11e8-9aef-57e2ac5fe238.png)

The format looks OK to me. The tool should at least show the error to the user.

**Comment by octref** [comment]
That's because everything is dumped into the output channel. The input you had was of this form:

```
[Trace - 4:21:27 PM] Sending request 'initialize - (0)'.
Params: {

}


Debugger listening on ws://127.0.0.1:6010/0956172b-cae0-49f0-9e99-af55cc1f5043
For help see https://nodejs.org/en/docs/inspector
[Trace - 4:21:28 PM] Received response 'initialize - (0)' in 673ms.
Result: {
    "capabilities": {
        "textDocumentSync": 1,
        "codeActionProvider": true
    }
}


[Info  - 4:21:28 PM] Linter is running.
[Trace - 4:21:28 PM] Sending notification 'initialized'.
Params: {}


[Trace - 4:21:28 PM] Sending notification 'workspace/didChangeConfiguration'.
```

The two lines on debugger come from `--inspect`.  I can handle the `[Info]` line and make the web app show an error.

**Comment by egamma** [comment]
@octref  the log parser should be more robust so that I do not have to manually edit the log output. The parser should only attempt to parse trace messages and skip over other output to stdout, like --inspect. It appears that the trace messages have a well defined format that can be distinguished from random output.

**Comment by octref** [comment]
This is handled fine now. I'll create a new issue for showing parsing error.

![image](https://user-images.githubusercontent.com/4033249/41886141-fc31308a-78af-11e8-8240-bbf3e1d1eae1.png)

**Comment by octref** [comment]
This issue was moved to Microsoft/language-server-protocol-inspector#10
